server:
  port: 8080

app:
  default_password: "admin123" # 默认密码，用于初始化超级管理员账号

database:
  type: postgres  # mysql, postgres, or sqlite
  enable_log: true  # 是否启用数据库日志（非SQL查询日志）
  log_level: "info" # silent, error, warn, info
  enable_sql_log: false # 是否启用SQL查询日志
  mysql:
    host: localhost
    port: 3306
    username: root
    password: root
    dbname: test
    max_idle_conns: 10
    max_open_conns: 100
  postgres:
    host: localhost
    port: 5432
    username: postgres
    password: 
    dbname: windz
    max_idle_conns: 10
    max_open_conns: 100
  sqlite:
    database: ./data.db

log:
  level: "debug"  # debug, info, warn, error
  format: "console" # console or json
  output: "both" # stdout, file, or both
  file_path: "logs/app.log"
